version: "3.6"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "100k"
    max-file: "1"

services:
  ignite-rentalx:
    restart: always
    user: "1000:1000"
    build:
      context: .
      target: dev
    volumes:
      - ".:/application"
    ports:
      - "3333:3333"
    logging: *default-logging
