version: "3.6"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "100k"
    max-file: "1"

services:
  postgres-rentx:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  ignite-rentalx:
    restart: always
    build:
      context: .
      target: dev
    environment:
      - WATCH_FILES=${WATCH_FILES}
    volumes:
      - ".:/application"
    ports:
      - "3333:3333"
      - "9229:9229"
    links:
      - postgres-rentx
    depends_on:
      - postgres-rentx
    logging: *default-logging

volumes:
  pgdata:
    driver: local
